# Generated by Django 5.1.7 on 2025-03-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expense',
        ),
    ]
