# Generated by Django 5.0.2 on 2025-04-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expensetype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('unexpected', 'Unexpected')], default='fixed', max_length=20),
        ),
        migrations.DeleteModel(
            name='ExpenseType',
        ),
    ]
