from .views.identifiers import (
    PROPERTY_TAG_IDENTIFIER,
    EXPENSE_TAG_IDENTIFIER,
    RENT_CONTRACT_TAG_IDENTIFIER,
    RENT_PAYMENT_TAG_IDENTIFIER,
    TENANT_TAG_IDENTIFIER,
    RESOURCES_TAG_IDENTIFIER,
)
