# Generated by Django 5.0.2 on 2025-04-09 02:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount_paid', models.FloatField()),
                ('payed_at', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('debit', 'Debit'), ('money', 'Money'), ('credit', 'Credit')], max_length=50)),
                ('rent_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_contract.rentcontract')),
            ],
            options={
                'verbose_name': 'Rent Payment',
                'verbose_name_plural': 'Rent Payments',
                'db_table': 'rent_payment',
            },
        ),
    ]
