# Generated by Django 5.1.7 on 2025-03-29 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('payed_at', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('debit', 'Debit Card'), ('money', 'Money'), ('credit', 'Credit Card')], max_length=50)),
                ('rent_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_contract.rentcontract')),
            ],
        ),
    ]
