# Generated by Django 5.1.7 on 2025-03-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentpayment',
            options={'verbose_name': 'Rent Payment', 'verbose_name_plural': 'Rent Payments'},
        ),
        migrations.AlterModelTable(
            name='rentpayment',
            table='rent_payment',
        ),
    ]
