# Generated by Django 5.0.2 on 2025-03-31 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payment', '0002_alter_rentpayment_options_alter_rentpayment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('debit', 'Debit'), ('money', 'Money'), ('credit', 'Credit')], max_length=50),
        ),
    ]
