# Generated by Django 5.0.2 on 2025-04-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rent_value',
            new_name='rent',
        ),
    ]
