# Generated by Django 5.0.2 on 2025-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_rent_value_property_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('rented', 'Rented'), ('maintance', 'Maintance'), ('reforbish', 'Reforbish')], default='free', max_length=20),
        ),
    ]
