# Generated by Django 5.0.2 on 2025-04-14 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
