# Generated by Django 5.0.2 on 2025-04-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
