# Generated by Django 5.0.2 on 2025-04-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='payments_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
