# Generated by Django 5.0.2 on 2025-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_contract', '0002_rentcontract_payments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
