FROM node:24-alpine

WORKDIR /code

COPY package.json tsconfig.json yarn.lock ./
COPY src ./src

RUN yarn install
RUN yarn build:prod
RUN yarn global add serve

RUN rm -rf src package.json tsconfig.json yarn.lock

CMD ["serve", "-s", "/code/build"]
