# Generated by Django 5.1.7 on 2025-03-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='tenant',
        ),
    ]
