FROM node:24-alpine

WORKDIR /code

COPY package.json tsconfig.json /code/
COPY src /code/src

RUN yarn
RUN yarn build:prod -- /code/
RUN yarn global add serve

RUN rm -r package.json tsconfig.json src

CMD ["serve", "-s", "/code/build"]
