FROM node:20

WORKDIR /code

COPY package.json tsconfig.json /code/
COPY src /code/src

RUN npm install
RUN npm run build:prod -- /code/
RUN npm install -g serve

RUN rm -r package.json tsconfig.json src

CMD ["serve", "-s", "/code/build"]
